# .github/workflows/caller.yml
name: Call Reusable Workflow

on:
  push:
    branches: [ main ]

jobs:
  call-tests:
    uses: ./.github/workflows/resuableworkflow.yml
    with:
      python-version: "3.11"
    outputs:
      test-result: ${{ steps.set-result.outputs.outcome }}

  print-result:
    runs-on: ubuntu-latest
    needs: call-tests
    steps:
      - run: echo "Test Result from reusable workflow: ${{ needs.call-tests.outputs.test-result }}"
