# .github/workflows/caller.yml
name: Call Reusable Workflow

on:
  push:
    branches: [ main ]

jobs:
  call-tests:
    uses: ./.github/workflows/reusableworkflow.yml
    with:
      python-version: "3.11"
    outputs:
      test-result: ${{ jobs.call-tests.outputs.test-result }}

  print-result:
    runs-on: ubuntu-latest
    needs: call-tests
    
